-- Hyprland Lua configuration
-- Variables are imported from nix_vars.lua which is generated by Nix
local v = require("nix_vars")

local terminal = v.terminal
local fileManager = v.fileManager
local browser = v.browser
local menu = "pkill rofi || rofi -calc-command \"echo -n '{result}' | wl-copy\" -calc-command-history"

------------------
---- MONITORS ----
------------------
hl.monitor({
    output   = "DP-1",
    mode     = "3440x1440@144",
    position = "0x0",
    scale    = "1",
})

-------------------
---- AUTOSTART ----
-------------------
hl.on("hyprland.start", function()
    hl.exec_cmd("uwsm app -- waybar")
    hl.exec_cmd("uwsm app -- lxqt-policykit-agent")
    hl.exec_cmd("uwsm app -- hyprpaper")
    hl.exec_cmd("uwsm app -- hypridle")
    hl.exec_cmd("uwsm app -- sh -c 'sleep 2 && keepassxc --minimized'")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("GBM_BACKEND", "nvidia-drm")

-----------------------
---- LOOK AND FEEL ----
-----------------------
hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 4,
        border_size = 2,
        col = {
            active_border = v.colors.lavender,
            inactive_border = v.colors.overlay0,
        },
        resize_on_border = false,
        allow_tearing = false,
        layout = "master",
    },

    decoration = {
        rounding = 4,
        active_opacity = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled = true,
            range = 4,
            render_power = 3,
            color = "rgba(1a1a1aee)",
        },

        blur = {
            enabled = true,
            size = 4,
            passes = 3,
            vibrancy = 0.2,
            popups = true,
        },
    },

    animations = {
        enabled = true,
    },
})

-- Animations
hl.curve("wind", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.curve("winIn", { type = "bezier", points = { { 0.1, 1.1 }, { 0.1, 1.1 } } })
hl.curve("winOut", { type = "bezier", points = { { 0.3, -0.3 }, { 0, 1 } } })
hl.curve("liner", { type = "bezier", points = { { 1, 1 }, { 1, 1 } } })

hl.animation({ leaf = "windows", enabled = true, speed = 6, bezier = "wind", style = "slide" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 6, bezier = "winIn", style = "slide" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 5, bezier = "winOut", style = "slide" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 5, bezier = "wind", style = "slide" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 6, bezier = "wind", style = "popin" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 5, bezier = "wind", style = "popin" })
hl.animation({ leaf = "border", enabled = true, speed = 1, bezier = "liner" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 30, bezier = "liner", style = "once" })
hl.animation({ leaf = "fade", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 5, bezier = "wind", style = "slidevert" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 5, bezier = "wind", style = "slide" })

hl.config({
    master = {
        new_status = "inherit",
        orientation = "right",
        mfact = 0.6,
    },
    misc = {
        vrr = 3,
        force_default_wallpaper = -1,
        disable_hyprland_logo = false,
    },
    group = {
        col = {
            border_active = v.colors.sapphire,
            border_inactive = v.colors.overlay0,
            border_locked_active = v.colors.red,
            border_locked_inactive = v.colors.overlay0,
        },
        groupbar = {
            enabled = true,
            render_titles = false,
            height = 3,
            col = {
                active = v.colors.sapphire,
                inactive = v.colors.surface1,
                locked_active = v.colors.red,
                locked_inactive = v.colors.surface1,
            },
        },
    },
    input = {
        kb_layout = "us,ru-pro",
        kb_options = "grp:caps_toggle, grp_led:caps",
        numlock_by_default = true,
        follow_mouse = 1,
        sensitivity = 0,
        touchpad = {
            natural_scroll = false,
        },
    },
    cursor = {
        no_hardware_cursors = true,
    },
})

---------------------
---- KEYBINDINGS ----
---------------------
local mainMod = "SUPER"

-- Screenshotting
hl.bind("CTRL + PRINT", hl.dsp.exec_cmd("smart-screenshot.sh output"))
hl.bind("SHIFT + PRINT", hl.dsp.exec_cmd("smart-screenshot.sh window"))
hl.bind("PRINT", hl.dsp.exec_cmd("smart-screenshot.sh region"))

-- Window Management
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("uwsm stop"))
hl.bind(mainMod .. " + F", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + W", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + O", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + I", hl.dsp.exec_cmd("~/.config/waybar/scripts/hypridle.sh --toggle"))

-- Mouse bindings
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Groups
hl.bind(mainMod .. " + G", hl.dsp.group.toggle())
hl.bind(mainMod .. " + N", hl.dsp.group.next())
hl.bind(mainMod .. " + P", hl.dsp.group.prev())

-- Vim-style Navigation (HJKL)
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + SHIFT + h", hl.dsp.window.move({ direction = "left" }))
hl.bind(mainMod .. " + SHIFT + l", hl.dsp.window.move({ direction = "right" }))
hl.bind(mainMod .. " + SHIFT + k", hl.dsp.window.move({ direction = "up" }))
hl.bind(mainMod .. " + SHIFT + j", hl.dsp.window.move({ direction = "down" }))

hl.bind(mainMod .. " + CTRL + h", hl.dsp.window.move({ into_group = "left" }))
hl.bind(mainMod .. " + CTRL + l", hl.dsp.window.move({ into_group = "right" }))
hl.bind(mainMod .. " + CTRL + k", hl.dsp.window.move({ into_group = "up" }))
hl.bind(mainMod .. " + CTRL + j", hl.dsp.window.move({ into_group = "down" }))
hl.bind(mainMod .. " + CTRL + G", hl.dsp.window.move({ out_of_group = true }))

-- Menus
hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd(menu .. " -show drun -modes \"drun,calc\""))
hl.bind(mainMod .. " + SHIFT + Space", hl.dsp.exec_cmd(menu .. " -show drun -modes \"drun,calc,run,filebrowser,window\""))

-- Workspaces
for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Special Workspace
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + CTRL + S", hl.dsp.window.move({ workspace = "special:magic", silent = true }))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Main programs
hl.bind(mainMod .. " + RETURN", hl.dsp.exec_cmd(terminal))

-- Media & Hardware
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"),
    { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
    { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
    { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
    { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true, repeating = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Submap: RESIZE
hl.bind(mainMod .. " + R", hl.dsp.submap("RE"))
hl.define_submap("RE", function()
    hl.bind("l", hl.dsp.window.resize({ x = 20, y = 0 }), { repeating = true })
    hl.bind("h", hl.dsp.window.resize({ x = -20, y = 0 }), { repeating = true })
    hl.bind("k", hl.dsp.window.resize({ x = 0, y = -20 }), { repeating = true })
    hl.bind("j", hl.dsp.window.resize({ x = 0, y = 20 }), { repeating = true })

    hl.bind("SHIFT + l", hl.dsp.window.resize({ x = 80, y = 0 }), { repeating = true })
    hl.bind("SHIFT + h", hl.dsp.window.resize({ x = -80, y = 0 }), { repeating = true })
    hl.bind("SHIFT + k", hl.dsp.window.resize({ x = 0, y = -80 }), { repeating = true })
    hl.bind("SHIFT + j", hl.dsp.window.resize({ x = 0, y = 80 }), { repeating = true })

    hl.bind("escape", hl.dsp.submap("reset"))
    hl.bind("return", hl.dsp.submap("reset"))
end)

-- Submap: LAUNCHER
hl.bind(mainMod .. " + A", hl.dsp.submap("AP"))
hl.define_submap("AP", function()
    hl.bind("t", function()
        hl.dispatch(hl.dsp.exec_cmd(terminal)); hl.dispatch(hl.dsp.submap("reset"))
    end)
    hl.bind("b",
        function()
            hl.dispatch(hl.dsp.exec_cmd(browser .. " --profile-directory=\"Profile 1\"")); hl.dispatch(hl.dsp.submap(
                "reset"))
        end)
    hl.bind("SHIFT + b",
        function()
            hl.dispatch(hl.dsp.exec_cmd(browser .. " --profile-directory=\"Profile 2\"")); hl.dispatch(hl.dsp.submap(
                "reset"))
        end)
    hl.bind("e", function()
        hl.dispatch(hl.dsp.exec_cmd(fileManager)); hl.dispatch(hl.dsp.submap("reset"))
    end)
    hl.bind("p", function()
        hl.dispatch(hl.dsp.exec_cmd("phpstorm")); hl.dispatch(hl.dsp.submap("reset"))
    end)
    hl.bind("w", function()
        hl.dispatch(hl.dsp.exec_cmd("webstorm")); hl.dispatch(hl.dsp.submap("reset"))
    end)

    hl.bind("escape", hl.dsp.submap("reset"))
end)

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------
hl.window_rule({
    name = "global-suppress-maximize",
    match = { class = ".*" },
    suppress_event = "maximize",
})

hl.window_rule({
    name = "xwayland-focus-fix",
    match = { class = "^$", title = "^$", xwayland = true },
    no_focus = true,
})

hl.window_rule({ name = "float-apps", match = { class = "Viewnior" }, float = true })
hl.window_rule({ name = "auth-dialogs", match = { title = "Authentication Required" }, float = true })

hl.window_rule({ name = "yandex-xsen1", match = { class = "[yY]andex-browser", title = ".*xsen1.*" }, workspace = 1 })
hl.window_rule({ name = "yandex-xsen2", match = { class = "[yY]andex-browser", title = ".*xsen2.*" }, workspace = 3 })
hl.window_rule({ name = "app-obsidian", match = { class = "obsidian" }, workspace = 2 })
hl.window_rule({ name = "app-ticktick", match = { class = "ticktick" }, workspace = 2 })
hl.window_rule({ name = "app-telegram", match = { class = "org\\.telegram\\.desktop" }, workspace = 3 })
hl.window_rule({ name = "app-social", match = { class = "(?i)(discord|spotify|plexamp|yandexmusic|yandex-music)" }, workspace = 4 })
hl.window_rule({ name = "app-steam", match = { class = "steam" }, workspace = "5 silent" })

hl.window_rule({
    name = "transparency-tagging",
    match = { class = "(?i)([yY]andex-browser|kitty|jetbrains-.*|obsidian|ticktick|discord|spotify|org\\.telegram\\.desktop|com\\.mitchellh\\.ghostty|dev\\.zed\\.Zed)" },
    tag = "+transparent",
})

hl.window_rule({
    name = "apply-transparency",
    match = { tag = "transparent" },
    opacity = "0.94 0.86",
})
