{
  config,
  lib,
  pkgs,
  ...
}:
let
  vars = import ./variables.nix { inherit config; };
  c = vars.colors;
  s = vars.settings;

  # Nix variables in Lua format for hyprland.lua to import
  nixVarsLua = ''
    -- Generated by Nix
    return {
      terminal = "${s.terminal}",
      fileManager = "${s.fileManager}",
      browser = "${s.browser}",
      colors = {
        rosewater = "${c.rosewater}",
        flamingo = "${c.flamingo}",
        pink = "${c.pink}",
        mauve = "${c.mauve}",
        red = "${c.red}",
        maroon = "${c.maroon}",
        peach = "${c.peach}",
        yellow = "${c.yellow}",
        green = "${c.green}",
        teal = "${c.teal}",
        sky = "${c.sky}",
        sapphire = "${c.sapphire}",
        blue = "${c.blue}",
        lavender = "${c.lavender}",
        text = "${c.text}",
        subtext1 = "${c.subtext1}",
        subtext0 = "${c.subtext0}",
        overlay2 = "${c.overlay2}",
        overlay1 = "${c.overlay1}",
        overlay0 = "${c.overlay0}",
        surface2 = "${c.surface2}",
        surface1 = "${c.surface1}",
        surface0 = "${c.surface0}",
        base = "${c.base}",
        mantle = "${c.mantle}",
        crust = "${c.crust}",
      }
    }
  '';

  # Helper to generate the variables.conf for Hyprlock or other legacy tools if needed
  variablesConf = ''
    $accent = ${s.accent}
    $accentAlpha = ${s.accentAlpha}
    $font = ${s.font}
    $wallpaper = ${s.wallpaper}

    $rosewater = ${c.rosewater}
    $flamingo = ${c.flamingo}
    $pink = ${c.pink}
    $mauve = ${c.mauve}
    $red = ${c.red}
    $maroon = ${c.maroon}
    $peach = ${c.peach}
    $yellow = ${c.yellow}
    $green = ${c.green}
    $teal = ${c.teal}
    $sky = ${c.sky}
    $sapphire = ${c.sapphire}
    $blue = ${c.blue}
    $lavender = ${c.lavender}
    $text = ${c.text}
    $textAlpha = ${c.textAlpha}
    $subtext1 = ${c.subtext1}
    $subtext0 = ${c.subtext0}
    $overlay2 = ${c.overlay2}
    $overlay1 = ${c.overlay1}
    $overlay0 = ${c.overlay0}
    $surface2 = ${c.surface2}
    $surface1 = ${c.surface1}
    $surface0 = ${c.surface0}
    $base = ${c.base}
    $mantle = ${c.mantle}
    $crust = ${c.crust}
  '';

in
{
  xdg.configFile."hypr/hyprland.lua".source = ./hyprland.lua;
  xdg.configFile."hypr/nix_vars.lua".text = nixVarsLua;
  xdg.configFile."hypr/hyprlock.conf".source = ./hyprlock.conf;
  xdg.configFile."hypr/variables.conf".text = variablesConf;

  # Static configs
  xdg.configFile."hypr/hypridle.conf".source = ./hypridle.conf;
  xdg.configFile."hypr/hyprpaper.conf".source = ./hyprpaper.conf;
  xdg.configFile."hypr/themes" = {
    source = ./themes;
    recursive = true;
  };
}
